version: '3.8'

services:
  db:
    container_name: healthify-db
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: healthify
    volumes:
      - postgres-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  postgres-db:
    driver: local
